# Generated by Django 5.0.3 on 2024-04-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sysuser", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flight_number",
                    models.CharField(max_length=50, verbose_name="航班号"),
                ),
                (
                    "departure_city",
                    models.CharField(max_length=100, verbose_name="出发城市"),
                ),
                ("arrival_city", models.CharField(max_length=100, verbose_name="到达城市")),
                ("departure_date", models.DateField(verbose_name="出发日期")),
                ("airline", models.CharField(max_length=100, verbose_name="航空公司")),
                (
                    "aircraft_type",
                    models.CharField(max_length=100, verbose_name="客机机型"),
                ),
                (
                    "departure_airport",
                    models.CharField(max_length=100, verbose_name="出发机场"),
                ),
                (
                    "arrival_airport",
                    models.CharField(max_length=100, verbose_name="到达机场"),
                ),
                ("departure_time", models.TimeField(verbose_name="出发时间")),
                ("arrival_time", models.TimeField(verbose_name="抵达时间")),
                ("cabin_type", models.CharField(max_length=100, verbose_name="客舱类型")),
                (
                    "ticket_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="机票价格"
                    ),
                ),
                ('status', models.CharField(max_length=100, verbose_name="状态"))
            ],
            options={
                "verbose_name": "航班信息",
                "verbose_name_plural": "航班信息",
                "db_table": "flight",
            },
        ),
        migrations.CreateModel(
            name="Flight2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "departure_city",
                    models.CharField(max_length=100, verbose_name="出发城市"),
                ),
                ("arrival_city", models.CharField(max_length=100, verbose_name="到达城市")),
                ("airline", models.CharField(max_length=100, verbose_name="航空公司")),
                (
                    "aircraft_type",
                    models.CharField(max_length=100, verbose_name="客机机型"),
                ),
                (
                    "departure_airport",
                    models.CharField(max_length=100, verbose_name="出发机场"),
                ),
                (
                    "arrival_airport",
                    models.CharField(max_length=100, verbose_name="到达机场"),
                ),
                ("cabin_type", models.CharField(max_length=100, verbose_name="客舱类型")),
                (
                    "ticket_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="机票价格￥"
                    ),
                ),
                ("departure_month", models.IntegerField(verbose_name="出发日期(月份)")),
                ("departure_day", models.IntegerField(verbose_name="出发日期(天)")),
                ("departure_hour", models.IntegerField(verbose_name="出发时间(小时)")),
                ("departure_minute", models.IntegerField(verbose_name="出发时间(分钟)")),
                ("arrival_hour", models.IntegerField(verbose_name="抵达时间(小时)")),
                ("arrival_minute", models.IntegerField(verbose_name="抵达时间(分钟)")),
                ("duration_minutes", models.IntegerField(verbose_name="持续时间(分钟)")),
            ],
            options={
                "verbose_name": "航班信息2",
                "verbose_name_plural": "航班信息2",
                "db_table": "flight2",
            },
        ),
        migrations.DeleteModel(
            name="CarInfo",
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.TextField(null=True, verbose_name="住址"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=255, unique=True, verbose_name="邮箱"),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(max_length=20, null=True, verbose_name="性别"),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="用户名"),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=255, verbose_name="密码"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=20, null=True, unique=True, verbose_name="电话"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="touxiang",
            field=models.CharField(max_length=255, null=True, verbose_name="头像"),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="用户id"
            ),
        ),
    ]
