# Generated by Django 5.0.3 on 2024-04-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sysuser", "0002_flight_flight2_delete_carinfo_alter_user_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlightInfo",
            fields=[
                (
                    "flight_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="航班 ID"
                    ),
                ),
                ("airline", models.CharField(max_length=100, verbose_name="航空公司")),
                ("flight", models.CharField(max_length=50, verbose_name="航班号")),
                ("airport_from", models.CharField(max_length=100, verbose_name="出发机场")),
                ("airport_to", models.CharField(max_length=100, verbose_name="到达机场")),
                ("day_of_week", models.IntegerField(verbose_name="星期")),
                ("time", models.TimeField(verbose_name="时间")),
                ("length", models.IntegerField(verbose_name="航班时长")),
                ("weather", models.CharField(max_length=100, verbose_name="天气")),
                ("delay", models.IntegerField(verbose_name="延误时间")),
            ],
            options={
                "verbose_name": "航班信息",
                "verbose_name_plural": "航班信息",
                "db_table": "flightinfo",
            },
        ),
    ]
