airports_data = [
    {"城市": "北京", "中文名称": "北京首都国际机场", "英文名称": "Beijing Capital International Airport", "IATA代码": "PEK"},
    {"城市": "北京", "中文名称": "北京大兴国际机场", "英文名称": "Beijing Daxing International Airport", "IATA代码": "PKX"},
    {"城市": "天津", "中文名称": "天津滨海国际机场", "英文名称": "Tianjin Binhai International Airport", "IATA代码": "TSN"},
    {"城市": "石家庄", "中文名称": "石家庄正定国际机场", "英文名称": "Shijiazhuang Zhengding International Airport", "IATA代码": "SJW"},
    {"城市": "太原", "中文名称": "太原武宿国际机场", "英文名称": "Taiyuan Wusu International Airport", "IATA代码": "TYN"},
    {"城市": "呼和浩特", "中文名称": "呼和浩特白塔国际机场", "英文名称": "Hohhot Baita International Airport", "IATA代码": "HET"},
    {"城市": "沈阳", "中文名称": "沈阳桃仙国际机场", "英文名称": "Shenyang Taoxian International Airport", "IATA代码": "SHE"},
    {"城市": "大连", "中文名称": "大连周水子国际机场", "英文名称": "Dalian Zhoushuizi International Airport", "IATA代码": "DLC"},
    {"城市": "长春", "中文名称": "长春龙嘉国际机场", "英文名称": "Changchun Longjia International Airport", "IATA代码": "CGQ"},
    {"城市": "哈尔滨", "中文名称": "哈尔滨太平国际机场", "英文名称": "Harbin Taiping International Airport", "IATA代码": "HRB"},
    {"城市": "上海", "中文名称": "上海浦东国际机场", "英文名称": "Shanghai Pudong International Airport", "IATA代码": "PVG"},
    {"城市": "上海", "中文名称": "上海虹桥国际机场", "英文名称": "Shanghai Hongqiao International Airport", "IATA代码": "SHA"},
    {"城市": "南京", "中文名称": "南京禄口国际机场", "英文名称": "Nanjing Lukou International Airport", "IATA代码": "NKG"},
    {"城市": "杭州", "中文名称": "杭州萧山国际机场", "英文名称": "Hangzhou Xiaoshan International Airport", "IATA代码": "HGH"},
    {"城市": "厦门", "中文名称": "厦门高崎国际机场", "英文名称": "Xiamen Gaoqi International Airport", "IATA代码": "XMN"},
    {"城市": "青岛", "中文名称": "青岛胶东国际机场", "英文名称": "Qingdao Jiaodong International Airport", "IATA代码": "TAO"},
    {"城市": "济南", "中文名称": "济南遥墙国际机场", "英文名称": "Jinan Yaoqiang International Airport", "IATA代码": "TNA"},
    {"城市": "福州", "中文名称": "福州长乐国际机场", "英文名称": "Fuzhou Changle International Airport", "IATA代码": "FOC"},
    {"城市": "郑州", "中文名称": "郑州新郑国际机场", "英文名称": "Zhengzhou Xinzheng International Airport", "IATA代码": "CGO"},
    {"城市": "武汉", "中文名称": "武汉天河国际机场", "英文名称": "Wuhan Tianhe International Airport", "IATA代码": "WUH"},
    {"城市": "长沙", "中文名称": "长沙黄花国际机场", "英文名称": "Changsha Huanghua International Airport", "IATA代码": "CSX"},
    {"城市": "广州", "中文名称": "广州白云国际机场", "英文名称": "Guangzhou Baiyun International Airport", "IATA代码": "CAN"},
    {"城市": "深圳", "中文名称": "深圳宝安国际机场", "英文名称": "Shenzhen Bao'an International Airport", "IATA代码": "SZX"},
    {"城市": "海口", "中文名称": "海口美兰国际机场", "英文名称": "Haikou Meilan International Airport", "IATA代码": "HAK"},
    {"城市": "三亚", "中文名称": "三亚凤凰国际机场", "英文名称": "Sanya Phoenix International Airport", "IATA代码": "SYX"},
    {"城市": "南宁", "中文名称": "南宁吴圩国际机场", "英文名称": "Nanning Wuxu International Airport", "IATA代码": "NNG"},
    {"城市": "成都", "中文名称": "成都双流国际机场", "英文名称": "Chengdu Shuangliu International Airport", "IATA代码": "CTU"},
    {"城市": "成都", "中文名称": "成都天府国际机场", "英文名称": "Chengdu Tianfu International Airport", "IATA代码": "TFU"},
    {"城市": "重庆", "中文名称": "重庆江北国际机场", "英文名称": "Chongqing Jiangbei International Airport", "IATA代码": "CKG"},
    {"城市": "昆明", "中文名称": "昆明长水国际机场", "英文名称": "Kunming Changshui International Airport", "IATA代码": "KMG"},
    {"城市": "贵阳", "中文名称": "贵阳龙洞堡国际机场", "英文名称": "Guiyang Longdongbao International Airport", "IATA代码": "KWE"},
    {"城市": "拉萨", "中文名称": "拉萨贡嘎国际机场", "英文名称": "Lhasa Gongga International Airport", "IATA代码": "LXA"},
    {"城市": "西安", "中文名称": "西安咸阳国际机场", "英文名称": "Xi'an Xianyang International Airport", "IATA代码": "XIY"},
    {"城市": "兰州", "中文名称": "兰州中川国际机场", "英文名称": "Lanzhou Zhongchuan International Airport", "IATA代码": "LHW"},
    {"城市": "乌鲁木齐", "中文名称": "乌鲁木齐地窝堡国际机场", "英文名称": "Urumqi Diwopu International Airport", "IATA代码": "URC"},
    {"城市": "银川", "中文名称": "银川河东国际机场", "英文名称": "Yinchuan Hedong International Airport", "IATA代码": "INC"},
    {"城市": "西宁", "中文名称": "西宁曹家堡国际机场", "英文名称": "Xining Caojiabao International Airport", "IATA代码": "XNN"},
    {"城市": "宁波", "中文名称": "宁波栎社国际机场", "英文名称": "Ningbo Lishe International Airport", "IATA代码": "NGB"},
    {"城市": "温州", "中文名称": "温州龙湾国际机场", "英文名称": "Wenzhou Longwan International Airport", "IATA代码": "WNZ"},
    {"城市": "珠海", "中文名称": "珠海金湾机场", "英文名称": "Zhuhai Jinwan Airport", "IATA代码": "ZUH"},
    {"城市": "桂林", "中文名称": "桂林两江国际机场", "英文名称": "Guilin Liangjiang International Airport", "IATA代码": "KWL"}
]

list1 = [city['城市'] for city in airports_data ]
print(list1)